"""baseline

Revision ID: 0e3a69e02c1d
Revises: 
Create Date: 2026-02-06 18:37:48.265481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3a69e02c1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('dest_path', sa.Text(), nullable=False),
    sa.Column('expected_hash', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_tasks'))
    )
    op.create_table('hardware_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gpu_vendor', sa.String(length=50), nullable=True),
    sa.Column('gpu_name', sa.String(length=255), nullable=True),
    sa.Column('vram_gb', sa.Float(), nullable=True),
    sa.Column('compute_capability', sa.Float(), nullable=True),
    sa.Column('cpu_tier', sa.String(length=20), nullable=True),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('storage_free_gb', sa.Float(), nullable=True),
    sa.Column('raw_report', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_snapshots'))
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('commercial_use', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('is_cloud_api', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('cloud', sa.JSON(), nullable=True),
    sa.Column('hardware', sa.JSON(), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_is_cloud_api'), ['is_cloud_api'], unique=False)

    op.create_table('model_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('variant_id', sa.String(length=100), nullable=False),
    sa.Column('precision', sa.String(length=50), nullable=False),
    sa.Column('vram_min_mb', sa.Integer(), nullable=False),
    sa.Column('vram_recommended_mb', sa.Integer(), nullable=True),
    sa.Column('download_size_gb', sa.Float(), nullable=True),
    sa.Column('quality_retention_percent', sa.Integer(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('platform_support', sa.JSON(), nullable=True),
    sa.Column('requires_nodes', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_variants_model_id_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_variants'))
    )
    with op.batch_alter_table('model_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_variants_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_variants_vram_min_mb'), ['vram_min_mb'], unique=False)

    op.create_table('installations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('variant_db_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('current_bytes', sa.Integer(), nullable=True),
    sa.Column('total_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_verified', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variant_db_id'], ['model_variants.id'], name=op.f('fk_installations_variant_db_id_model_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installations')),
    sa.UniqueConstraint('local_path', name=op.f('uq_installations_local_path'))
    )
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installations_model_id'), ['model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installations_model_id'))

    op.drop_table('installations')
    with op.batch_alter_table('model_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_variants_vram_min_mb'))
        batch_op.drop_index(batch_op.f('ix_model_variants_model_id'))

    op.drop_table('model_variants')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_is_cloud_api'))
        batch_op.drop_index(batch_op.f('ix_models_category'))

    op.drop_table('models')
    op.drop_table('hardware_snapshots')
    op.drop_table('download_tasks')
    # ### end Alembic commands ###
